# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.
  config.vm.box = "centos/7"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    # vb.gui = true
  
    # Customize the amount of memory on the VM:
    vb.memory = "1536"
  end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Define a Vagrant Push strategy for pushing to Atlas. Other push strategies
  # such as FTP and Heroku are also available. See the documentation at
  # https://docs.vagrantup.com/v2/push/atlas.html for more information.
  # config.push.define "atlas" do |push|
  #   push.app = "YOUR_ATLAS_USERNAME/YOUR_APPLICATION_NAME"
  # end

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  config.vm.provision "shell", inline: <<-SHELL
    sudo yum -y update
    sudo yum -y install epel-release
    sudo yum -y install php php-pdo vim less php-gd php-enchant mariadb-server php-mysql php-intl php-mcrypt hunspell-nl
    sudo sed -i 's#DocumentRoot "/var/www/html"#DocumentRoot "/vagrant/public"#' /etc/httpd/conf/httpd.conf
    sudo sed -i 's#<Directory "/var/www/html"#<Directory "/vagrant/public"#' /etc/httpd/conf/httpd.conf
    sudo sed -i "s#AllowOverride None#AllowOverride All#" /etc/httpd/conf/httpd.conf
    sudo sed -i "s#DirectoryIndex index.html index.html.var#DirectoryIndex index.html index.php#" /etc/httpd/conf/httpd.conf
    sudo sed -i 's%#ServerName www.example.com:80%ServerName localhost%' /etc/httpd/conf/httpd.conf
    sudo sed -i 's%User apache%User vagrant%' /etc/httpd/conf/httpd.conf
    sudo sed -i 's%Group apache%Group vagrant%' /etc/httpd/conf/httpd.conf
    sudo sed -i 's%EnableSendfile on%EnableSendfile off%' /etc/httpd/conf/httpd.conf
    sudo sed -i 's%;date.timezone =%date.timezone = "Europe/Amsterdam"%' /etc/php.ini
    sudo chown -R root:vagrant /var/lib/php/session
    systemctl start httpd.service
    sudo chkconfig httpd on
    systemctl start mariadb.service
    sudo chkconfig mariadb on
    sudo iptables -F
    sudo service iptables save

    if [ -e "/vagrant/provision.sh" ]
    then
        echo "starting project privisioning.."
        /bin/bash /vagrant/provision.sh
    fi
    echo "provision done.."
  SHELL
end
